"""add schedule_overrides table

Revision ID: 178f03c04354
Revises: c59db199a117
Create Date: 2025-11-25 13:16:21.296494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178f03c04354'
down_revision: Union[str, None] = 'c59db199a117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False, comment='Original schedule entry being overridden'),
    sa.Column('override_member_id', sa.Integer(), nullable=False, comment='Team member covering the shift'),
    sa.Column('original_member_name', sa.String(length=100), nullable=False, comment='Original assignee at time of override'),
    sa.Column('override_member_name', sa.String(length=100), nullable=False, comment='Override assignee at time of override'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Reason for override (vacation, sick, swap, etc.)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active, cancelled, completed'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='Admin username who created override'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True, comment='When override was cancelled (if applicable)'),
    sa.ForeignKeyConstraint(['override_member_id'], ['team_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_override_date_range', 'schedule_overrides', ['created_at'], unique=False)
    op.create_index('idx_override_schedule_status', 'schedule_overrides', ['schedule_id', 'status'], unique=False)
    op.create_index(op.f('ix_schedule_overrides_created_at'), 'schedule_overrides', ['created_at'], unique=False)
    op.create_index(op.f('ix_schedule_overrides_id'), 'schedule_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_overrides_override_member_id'), 'schedule_overrides', ['override_member_id'], unique=False)
    op.create_index(op.f('ix_schedule_overrides_schedule_id'), 'schedule_overrides', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_overrides_status'), 'schedule_overrides', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_overrides_status'), table_name='schedule_overrides')
    op.drop_index(op.f('ix_schedule_overrides_schedule_id'), table_name='schedule_overrides')
    op.drop_index(op.f('ix_schedule_overrides_override_member_id'), table_name='schedule_overrides')
    op.drop_index(op.f('ix_schedule_overrides_id'), table_name='schedule_overrides')
    op.drop_index(op.f('ix_schedule_overrides_created_at'), table_name='schedule_overrides')
    op.drop_index('idx_override_schedule_status', table_name='schedule_overrides')
    op.drop_index('idx_override_date_range', table_name='schedule_overrides')
    op.drop_table('schedule_overrides')
    # ### end Alembic commands ###
