"""add completed_at to schedule_overrides

Revision ID: d91648dc4f04
Revises: 178f03c04354
Create Date: 2025-12-02 15:20:08.131564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91648dc4f04'
down_revision: Union[str, None] = '178f03c04354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_overrides', sa.Column('completed_at', sa.DateTime(), nullable=True, comment='When override was marked completed (schedule date passed)'))
    op.drop_index('ix_team_members_phone', table_name='team_members')
    op.create_index(op.f('ix_team_members_phone'), 'team_members', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_members_phone'), table_name='team_members')
    op.create_index('ix_team_members_phone', 'team_members', ['phone'], unique=False)
    op.drop_column('schedule_overrides', 'completed_at')
    # ### end Alembic commands ###
